#!/usr/bin/env bash

function state {
	gsettings get org.gnome.desktop.interface
}

function toggle {
	eww update game="$(get)"
	$HOME/.config/hypr/scripts/gamemode
}

if [[ $1 == 'toggle' ]]; then toggle; fi
if [[ $1 == 'get' ]]; then state; fi
