#!/usr/bin/env bash

# Defined
# ---------------------------------------------------------
function toggle_menu {
	MAIN=$(eww get main_monitor)
	hyprctl keyword blurls "remove,gtk-layer-shell"
	STATE=$(eww windows | grep $1$MAIN | awk '{print substr ($0, 0, 1)}')
	if [[ $STATE == '*' ]]; then
		if [[ $1 == '*' ]]; then hyprctl keyword blurls "remove,gtk-layer-shell"; fi
		eww close $1$MAIN
	else
		eww open $1$MAIN
	fi
}

function checkupdate {
	wezterm start --always-new-process -e $SHELL -c 'paru -Syu --noconfirm' notify-send "Morgana" "Upgrade complete! Our window manager is purring like a finely-tuned engine." -i ~/.config/hypr/assets/icons/morgana/awesome.png &
}

function network {
	nm-connection-editor
}

function config {
	$VISUAL $HOME/.config/hypr
}

function screenshot {
	DIR="$HOME/Pictures/Screenshots"
	mkdir -p $DIR

	if [[ $1 == 'screen' ]]; then
		distrobox-enter -n Arch -- hyprshot -m output -o $DIR
	else
		distrobox-enter -n Arch -- hyprshot -m region -o $DIR
	fi
}

# --------------------------------------------------------
# Aplications
if [[ $1 == 'pavu' ]]; then pavucontrol; fi
if [[ $1 == 'network' ]]; then network; fi
if [[ $1 == 'checkupdate' ]]; then checkupdate; fi
if [[ $1 == 'brightness' ]]; then wl-gammactl; fi
if [[ $1 == 'bluetooth' ]]; then blueberry; fi
if [[ $1 == 'toggle_menu' ]]; then toggle_menu $2; fi
if [[ $1 == 'close_calendar' ]]; then close_calendar; fi
if [[ $1 == 'picker' ]]; then picker; fi
if [[ $1 == 'config' ]]; then config; fi
if [[ $1 == 'screenshot' ]]; then screenshot $2; fi

# --------------------------------------------------
#        Dock Aplications
if [[ $1 == 'firefox' ]]; then firefox; fi
if [[ $1 == 'terminal' ]]; then wezterm; fi
if [[ $1 == 'file-manager' ]]; then thunar; fi
if [[ $1 == 'editor' ]]; then wezterm -e nvim; fi
if [[ $1 == 'programmer' ]]; then godot; fi
