#!/bin/bash

# Common paths
config_path="$HOME/.config"
user_path="$HOME"
icons_path="/usr/share/icons/"
themes_path="/usr/share/sddm/themes/"
fonts_path="/usr/share/fonts/"

# Function to move files
move_files() {
  src=$1
  dest=$2
  if [ -e "$src" ]; then
    mv "$src" "$dest" && echo "Moved $src to $dest successfully" || echo "Error moving $src to $dest"
  else
    echo "$src not found"
  fi
}

# Function to remove files
remove_files() {
  file=$1
  if [ -e "$file" ]; then
    rm -r "$file" && echo "Removed $file successfully" || echo "Error removing $file"
  else
    echo "$file not found"
  fi
}

# Check command line argument
if [ "$1" == "--add" ]; then
  move_files "cava Kvantum ranger Thunar eww neofetch retroarch wezterm ags gtklock nvim Roms wofi browsh hypr quotes starship" "$config_path"
  move_files ".zshrc" "$user_path"
  move_files "icons" "$icons_path"
  move_files "slice" "$themes_path"
  move_files "fonts" "$fonts_path"
elif [ "$1" == "--remove" ]; then
  remove_files "$config_path/cava Kvantum ranger Thunar eww neofetch retroarch wezterm ags gtklock nvim Roms wofi browsh hypr quotes starship"
  remove_files "$user_path/.zshrc"
  remove_files "$icons_path/pixelfun2-dracula Windows-Beuty"
  remove_files "$themes_path/slice"
  remove_files "$fonts_path/Minecraft.ttf Monocraft.ttf"
else
  echo "Installer and remover for the repository, follow the instructions according to your needs."
  echo "Usage: ./install argument"
  echo "--add: This will add all files to their respective directories."
  echo "--remove: Use remove if you no longer need or want to keep these files. Warning: this will delete all files from the repository, so if you want to keep some intact, I suggest you do it manually."
fi
