#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config"
RASI="$DIR/rofi/themes/asroot.rasi"
ASROOT="$HOME/.config/hypr/scripts/hyproot"

# Options
# follow the same steps if you want to add more root access. add options and command
layout=$(cat ${RASI} | grep 'USE_ICON' | cut -d'=' -f2)
if [[ "$layout" == 'NO' ]]; then
	option_1="  Sddm Config"
	option_2=" Thunar"
	option_3=" Bleachbit"
	option_4=" Mugshot"
	option_5=" TimeShift"
else
	option_1=" "
	option_2=" "
	option_3=" "
	option_4=" "
	option_5=" "
fi

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-p "$prompt" \
		-mesg "$mesg" \
		-markup-rows \
		-theme ${RASI}
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5" | rofi_cmd
}

# Execute Command
run_cmd() {
	if [[ "$1" == '--opt1' ]]; then
		${ASROOT} "sddm-config-editor"
	elif [[ "$1" == '--opt2' ]]; then
		${ASROOT} 'thunar'
	elif [[ "$1" == '--opt3' ]]; then
		${ASROOT} 'bleachbit'
	elif [[ "$1" == '--opt4' ]]; then
		${ASROOT} 'mugshot'
	elif [[ "$1" == '--opt5' ]]; then
		${ASROOT} "-E env XAUTHORITY=$XAUTHORITY timeshift-gtk"
	fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
$option_1)
	run_cmd --opt1
	;;
$option_2)
	run_cmd --opt2
	;;
$option_3)
	run_cmd --opt3
	;;
$option_4)
	run_cmd --opt4
	;;
$option_5)
	run_cmd --opt5
	;;
esac
