#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# ██████╗ ██████╗ ██╗ ██████╗ ██╗  ██╗████████╗███╗   ██╗███████╗███████╗
# ██╔══██╗██╔══██╗██║██╔════╝ ██║  ██║╚══██╔══╝████╗  ██║██╔════╝██╔════╝
# ██████╔╝██████╔╝██║██║  ███╗███████║   ██║   ██╔██╗ ██║█████╗  ███████╗
# ██╔══██╗██╔══██╗██║██║   ██║██╔══██║   ██║   ██║╚██╗██║██╔══╝  ╚════██║
# ██████╔╝██║  ██║██║╚██████╔╝██║  ██║   ██║   ██║ ╚████║███████╗███████║
# ╚═════╝ ╚═╝  ╚═╝╚═╝ ╚═════╝ ╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝╚══════╝╚══════╝
#
# Autor = Shen Blaskowitz
# Inspiration = https://github.com/adi1090x
# Follow Me = https://github.com/Shentxt
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#                 Executed Brightness
#
# a simple brightness script
#
# required to function
# --------------------
# wlsunset: brightness
# dunst: notify
# awk: print the message
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
current_brightness=$(xrandr --current --verbose | grep -i brightness | awk '{print $2}')

# Run the wlsunset command to update the brightness
wlsunset -S 8:00 -s 8:22 >/dev/null 2>&1

# Get the new brightness value after the change
new_brightness=$(xrandr --current --verbose | grep -i brightness | awk '{print $2}')

# Compare brightness values ​​to determine if they changed
if [[ "$new_brightness" != "$current_brightness" ]]; so
if [[ "$new_brightness" < "$current_brightness" ]]; so
notify-send "Brightnes Dark"
the rest
notify-send "Brightnes Light"
fi
fi
