#!/usr/bin/env bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# ██████╗ ██████╗ ██╗      ██████╗ ██████╗ ██████╗ ██╗ ██████╗██╗  ██╗███████╗██████╗
# ██╔════╝██╔═══██╗██║     ██╔═══██╗██╔══██╗██╔══██╗██║██╔════╝██║ ██╔╝██╔════╝██╔══██╗
# ██║     ██║   ██║██║     ██║   ██║██████╔╝██████╔╝██║██║     █████╔╝ █████╗  ██████╔╝
# ██║     ██║   ██║██║     ██║   ██║██╔══██╗██╔═══╝ ██║██║     ██╔═██╗ ██╔══╝  ██╔══██╗
# ╚██████╗╚██████╔╝███████╗╚██████╔╝██║  ██║██║     ██║╚██████╗██║  ██╗███████╗██║  ██║
#  ╚═════╝ ╚═════╝ ╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚═╝     ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
#
# Autor = Shen Blaskowitz
# Follow Me = https://github.com/Shentxt
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#                 Executed Colorpicker
#
# a simple colorpicker script
#
# required to function
# --------------------
# hyprpicker: colorpicker
# hyprctl: notify
# wl-paste: past color
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Require hyprpicker past color
color_output=$(hyprpicker)

# Copy the output to the clipboard
echo "$color_output" | wl-copy

# Get the hex name from the clipboard
hex_color=$(wl-paste)

if [[ -n "$hex_color" ]]; then
	notify-send "Morgana" "That color is so elegant, #${hex_color}. You have an eye for elegance!" -i ~/.config/hypr/assets/icons/morgana/ok.png
	paplay ~/.config/hypr/assets/effects/pick.ogg &>/dev/null
else
	notify-send "Morgana" "Seems like the color selection was canceled or no color was detected. Don't worry, we'll find the perfect color next time!" -i ~/.config/hypr/assets/icons/morgana/critic.png
	paplay ~/.config/hypr/assets/effects/alert.ogg &>/dev/null
fi
