#!/usr/bin/env sh

HYPRGAMEMODE=$(hyprctl getoption animations:enabled | sed -n '2p' | awk '{print $2}')
if [ $HYPRGAMEMODE = 1 ]; then
	hyprctl --batch "\
        keyword animations:enabled 0;\
        keyword decoration:drop_shadow 0;\
        keyword blur:blur 0;\
        keyword general:gaps_in 0;\
        keyword general:border_size 0;\
        keyword decoration:rounding 0;\
        keyword decoration:opacity 0;"
	notify-send "Morgana" "Ready for the hot adventure!?, it's time to leave!!" -i ~/.config/hypr/assets/icons/morgana/awesome.png
        paplay ~/.config/hypr/assets/effects/system.ogg &>/dev/null
	exit
fi
hyprctl reload
pkill ags
ags 

notify-send "Morgana" "ah! not now, not back to the real world" -i ~/.config/hypr/assets/icons/morgana/awesome.png
paplay ~/.config/hypr/assets/effects/system.ogg &>/dev/null
