#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>

# directory
DIR="$HOME/.config/hypr"

# rofi sudo askpass helper
export SUDO_ASKPASS="$DIR"/scripts/askpass

# execute the application
xhost +si:localuser:root
sudo -A -E $1
