#!/bin/sh

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# ██████╗ ██████╗  █████╗  ██████╗██╗████████╗██╗   ██╗
# ██╔═══██╗██╔══██╗██╔══██╗██╔════╝██║╚══██╔══╝╚██╗ ██╔╝
# ██║   ██║██████╔╝███████║██║     ██║   ██║    ╚████╔╝ 
# ██║   ██║██╔═══╝ ██╔══██║██║     ██║   ██║     ╚██╔╝  
# ╚██████╔╝██║     ██║  ██║╚██████╗██║   ██║      ██║   
#  ╚═════╝ ╚═╝     ╚═╝  ╚═╝ ╚═════╝╚═╝   ╚═╝      ╚═╝   
#
# Autor = Selmer443
# Inspiration = https://github.com/Selmer443
# Follow Me = https://github.com/Shentxt
#  
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#                 Executed Opacity
#
# a simple opacity script (Only Hyprland)
# 
# required to function
# -------------------- 
# hyprctl: composer of hypr
# 
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# it is used to work the opacity of the integrated compositor in a more extensive way

# use hypercyl, and check if it is greater than 0.80, if so continue
opacity_val=$(hyprctl getoption decoration:active_opacity | grep float)
echo "$opacity_val"
if [[ "$opacity_val" == "	float: 0.800000" ]]; then
    
# if it detects that it is 0.80 it continues, and establishes three rules
    echo "float 0.8 detected"
    hyprctl --batch "keyword decoration:active_opacity 0.6 ; keyword decoration:inactive_opacity 0.6 ; keyword decoration:fullscreen_opacity 1.0"
else
    
# same as above
    echo "float 1.0 detected"
    hyprctl --batch "keyword decoration:active_opacity 0.6 ; keyword decoration:inactive_opacity 0.6 ; keyword decoration:fullscreen_opacity 1.0"
fi
