#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# ██████╗ ███████╗██╗      ██████╗  █████╗ ██████╗ 
# ██╔══██╗██╔════╝██║     ██╔═══██╗██╔══██╗██╔══██╗
# ██████╔╝█████╗  ██║     ██║   ██║███████║██║  ██║
# ██╔══██╗██╔══╝  ██║     ██║   ██║██╔══██║██║  ██║
# ██║  ██║███████╗███████╗╚██████╔╝██║  ██║██████╔╝
# ╚═╝  ╚═╝╚══════╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚═════╝  
#
# Autor = Selmer443
# Inspiration = https://github.com/Selmer443
# Follow Me = https://github.com/Shentxt
#  
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#                 Executed Reload
#
# a simple reload script
# 
# no requirement
# -------------- 
# 
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# this is useful to automatically remove services, edit it if you have another service you want to reload

# wait a second before starting
sleep 1

# stops the following
killall xdg-desktop-portal-hyprland
killall xdg-desktop-portal-wlr
killall xdg-desktop-portal
/usr/libexec/xdg-desktop-portal-hyprland &

# wait two seconds before starting and initial before removed
sleep 2
/usr/lib/xdg-desktop-portal &
