#!/bin/sh

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# ██╗    ██╗ █████╗ ██╗     ██╗     ██████╗  █████╗ ██████╗ ███████╗██████╗
# ██║    ██║██╔══██╗██║     ██║     ██╔══██╗██╔══██╗██╔══██╗██╔════╝██╔══██╗
# ██║ █╗ ██║███████║██║     ██║     ██████╔╝███████║██████╔╝█████╗  ██████╔╝
# ██║███╗██║██╔══██║██║     ██║     ██╔═══╝ ██╔══██║██╔═══╝ ██╔══╝  ██╔══██╗
# ╚███╔███╔╝██║  ██║███████╗███████╗██║     ██║  ██║██║     ███████╗██║  ██║
#  ╚══╝╚══╝ ╚═╝  ╚═╝╚══════╝╚══════╝╚═╝     ╚═╝  ╚═╝╚═╝     ╚══════╝╚═╝  ╚═╝
#
# Autor = Axenide
# Follow = https://github.com/Axenide/Dotfiles
# Follow Me = https://github.com/Shentxt
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#                 Executed Wallpaper
#
# a simple wallpaper script
#
# use of swww = swww --help more informations
# There is also simple,
# which simply fades into the new image, any, which starts at a random point with either center of outer transitions,
# and random, which selects a transition effect at random.
#
# required to function
# --------------------
# wofi: launcher
# swww: wallpaper
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

WALLPAPERS_DIR="$HOME/.config/hypr/assets/walls"
CURRENT_WALL_DIR="/tmp"
CMD="wofi --show dmenu --preview='file://$WALLPAPERS_DIR/{}'"

choice=$(
	ls --escape "$WALLPAPERS_DIR" |
		while read A; do echo -en "$A\x00icon\x1f$WALLPAPERS_DIR/$A\n"; done |
		$CMD -p "󰸉  Wallpaper"
)

wallpaper="$WALLPAPERS_DIR/$choice"

if [ "$XDG_CURRENT_DESKTOP" = "sway" ]; then
	swaymsg output "*" bg "$wallpaper" "stretch"
	exit 0
else
	swww img -t any --transition-bezier 0.0,0.0,1.0,1.0 --transition-duration 1 --transition-step 255 --transition-fps 60 "$wallpaper" &&
		wal -i "$wallpaper" &&
		ln -sf "$wallpaper" "$CURRENT_WALL_DIR"/current.wall
fi
