#!/usr/bin/env bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# ██╗    ██╗███╗   ███╗██████╗ ███████╗██╗      ██████╗  █████╗ ██████╗
# ██║    ██║████╗ ████║██╔══██╗██╔════╝██║     ██╔═══██╗██╔══██╗██╔══██╗
# ██║ █╗ ██║██╔████╔██║██████╔╝█████╗  ██║     ██║   ██║███████║██║  ██║
# ██║███╗██║██║╚██╔╝██║██╔══██╗██╔══╝  ██║     ██║   ██║██╔══██║██║  ██║
# ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║███████╗███████╗╚██████╔╝██║  ██║██████╔╝
#  ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝╚══════╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚═════╝
#
# Autor = Shen Blaskowitz
# Follow Me = https://github.com/Shentxt
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#                 Executed Windos Manager Reload
#
# a simple WM reload script
#
# required to function (only hyprland)
# --------------------
# hyprctl: wmreload
# hyprctl: notify
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
sleep 1 && hyprctl reload

#pkill Aplications
#pkill eww
pkill ags

# Start Aplications
#~/.config/eww/init
~/.config/hypr/scripts/wallrandom
ags &

#this script reloads the desktop
notify-send "Morgana" "Upgrade complete! Our window manager is purring like a finely-tuned engine." -i ~/.config/hypr/assets/icons/morgana/awesome.png
paplay ~/.config/hypr/assets/effects/system.ogg &>/dev/null
