-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
--
--  Autor = Shen Blaskowitz
--  Followme = https://github.com/Shentxt
--
-- ██╗  ██╗███████╗██╗   ██╗██████╗ ██╗███╗   ██╗██████╗ ███████╗
-- ██║ ██╔╝██╔════╝╚██╗ ██╔╝██╔══██╗██║████╗  ██║██╔══██╗██╔════╝
-- █████╔╝ █████╗   ╚████╔╝ ██████╔╝██║██╔██╗ ██║██║  ██║███████╗
-- ██╔═██╗ ██╔══╝    ╚██╔╝  ██╔══██╗██║██║╚██╗██║██║  ██║╚════██║
-- ██║  ██╗███████╗   ██║   ██████╔╝██║██║ ╚████║██████╔╝███████║
-- ╚═╝  ╚═╝╚══════╝   ╚═╝   ╚═════╝ ╚═╝╚═╝  ╚═══╝╚═════╝ ╚══════╝
--
-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
--                 Config Keys
--
-- it's just a configuration Keys file
--
-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here by
--
-- read respective wikis
-- - - - - - - - - - - -
-- wiki: https://www.vim.org/
-- wiki: https://www.lua.org/docs.html
--
-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

-----------------------------------------------------------
--             Neovim Shortcuts Main
--1
--  Keys
-- - - -
-- leader (Space)
-- C (Control)
-- A (Alt)
-- S (Shift)
-- win (No Recommend)
--
-----------------------------------------------------------
